name: build-rolling-self-hosted

on:
  schedule:
    - cron: 0 12 * * *
  workflow_dispatch:

jobs:
  build-rolling-self-hosted:
    runs-on: [self-hosted, linux, ARM64]
    steps:
      - name: Trigger workflow
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'build-main-self-hosted.yaml',
              ref: 'rolling',
            })
